name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-push-to-azure:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: azure/docker-login@v1
      with:
        login-server: 'azurehospitalitydocker.azurecr.io' # default: index.docker.io
        username: 'azurehospitalitydocker'
        password: 'HjXjHbqWd=WCGnDFswYkTKCz=ZG9yn7J'

    - name: Build the Docker image
      run: | 
          docker build . --file Dockerfile --tag azurehospitalitydocker.azurecr.io/my-image-name:$(date +%u%I%M)
          docker push azurehospitalitydocker.azurecr.io/my-image-name:$(date +%u%I%M)
          
  build-and-push-to-gcr:
    name: "Bulding and pushing images"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Building and pushing the image"
        uses: ./
        with:
          gcloud_service_key: ${{ secrets.JSON_GCLOUD_SERVICE_ACCOUNT_JSON }}
          registry: gcr.io
          project_id: pro-chesta
          image_name: hello-world-by-push-to-gcr
          image_tag: test-${{ github.sha }}, ${{ github.sha }}
          dockerfile: ./test/Dockerfile.test
          context: ./test
          target: build
   
