name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: azure/docker-login@v1
      with:
        login-server: 'azurehospitalitydocker.azurecr.io' # default: index.docker.io
        username: 'azurehospitalitydocker'
        password: 'HjXjHbqWd=WCGnDFswYkTKCz=ZG9yn7J'

    - name: Build the Docker image
      run: | 
          docker build . --file Dockerfile --tag azurehospitalitydocker.azurecr.io/my-image-name:$(date +%s)
          docker push azurehospitalitydocker.azurecr.io/my-image-name:$(date +%s)
